=== shinmanoko/ProjetEncadre-2/doc_stru/exos/Exo3/bibliographie.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT document (livre,article)>
<!ATTLIST document
  xmlns CDATA #FIXED ''>

<!ELEMENT livre (titre,contenu,information)>
<!ATTLIST livre
  xmlns CDATA #FIXED ''
  avis_personnel CDATA #REQUIRED>

<!ELEMENT article (titre,auteur,journal,Date_Publication,adresse)>
<!ATTLIST article
  xmlns CDATA #FIXED ''
  avis_personnel CDATA #REQUIRED>

<!ELEMENT contenu (page|tome)+>
<!ATTLIST contenu
  xmlns CDATA #FIXED ''>

<!ELEMENT information (auteur,editeur,collection,langue,iban)>
<!ATTLIST information
  xmlns CDATA #FIXED ''>

<!ELEMENT journal (#PCDATA)>
<!ATTLIST journal
  xmlns CDATA #FIXED ''>

<!ELEMENT Date_Publication (#PCDATA)>
<!ATTLIST Date_Publication
  xmlns CDATA #FIXED ''>

<!ELEMENT adresse (#PCDATA)>
<!ATTLIST adresse
  xmlns CDATA #FIXED ''>

<!ELEMENT page (#PCDATA)>
<!ATTLIST page
  xmlns CDATA #FIXED ''>

<!ELEMENT tome (#PCDATA)>
<!ATTLIST tome
  xmlns CDATA #FIXED ''
  nb_pages CDATA #REQUIRED>

<!ELEMENT editeur (#PCDATA)>
<!ATTLIST editeur
  xmlns CDATA #FIXED ''>

<!ELEMENT collection (#PCDATA)>
<!ATTLIST collection
  xmlns CDATA #FIXED ''>

<!ELEMENT langue (#PCDATA)>
<!ATTLIST langue
  xmlns CDATA #FIXED ''>

<!ELEMENT iban (#PCDATA)>
<!ATTLIST iban
  xmlns CDATA #FIXED ''>

<!ELEMENT titre (#PCDATA)>
<!ATTLIST titre
  xmlns CDATA #FIXED ''>

<!ELEMENT auteur (#PCDATA)>
<!ATTLIST auteur
  xmlns CDATA #FIXED ''>

=== shinmanoko/ProjetEncadre-2/doc_stru/exos/Exo3/bibliographie.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "bibliographie.dtd">
<document>
    <livre avis_personnel="">
       <titre>
        Les miserables
       </titre>
        <contenu>
            <tome nb_pages="100">La Fantine</tome>
            <page>0-100</page>
            <tome nb_pages="100">Cosette</tome>
            <page>100-200</page>
            <tome nb_pages="100">Marius</tome>
            <page>200-300</page>
            <tome nb_pages="100">Jean Valjean</tome>
            <page>300-400</page>
        </contenu>
        <information>
            <auteur>Victor Hugo</auteur>
            <editeur>Ecole des loisirs</editeur>
            <collection>Classique abrégé</collection>
            <langue>français</langue>
            <iban>211215351</iban>
        </information>
    </livre>
    <article avis_personnel="">
        <titre>
            Une manifestation contre les «violences policières» émaillée d'incidents
        </titre>
        <auteur>
            AFP agence
        </auteur>
        <journal>
            Le figaro
        </journal>
        <Date_Publication>
            19/03/2017 à 18:43
        </Date_Publication>
        <adresse>
            http://www.lefigaro.fr/actualite-france/2017/03/19/01016-20170319ARTFIG00150-des-milliers-de-manifestants-a-paris-contre-les-violences-policieres.php
        </adresse>
      </article>
</document>
